apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wpapp
  name: wordpress-app-np
spec:
  containers:
  - image: wordpress:latest
    name: con1
    env: 
    - name: WORDPRESS_DB_HOST
      value: mydb-svc
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: test123
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_TABLE_PREFIX
      value: wp_
    ports:
    - containerPort: 80
    
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-app-svc
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30124
  selector:
    app: wpapp
  type: LoadBalancer
