apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydep
spec:
   replicas: 1
   selector:
     matchLabels:
       app: mango
   template:
     metadata: 
        labels:
          app: mango
     spec:
        containers:
        - name: con1
          image: nginx:latest
          ports: 
          - containerPort: 80
          envFrom:
          - configMapRef:
              name: myenv
          volumeMounts:
          - name: myvol
            mountPath: /usr/share/nginx/html 
        volumes:
        - name: myvol
          configMap:
             name: myindex
 
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  type: NodePort
  selector:
    app: mango
  ports:
  - port: 80
    nodePort: 30123


