apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mydep
spec:
   replicas: 3
   selector:
     matchLabels:
       app: mango
   template:
     metadata: 
        labels:
          app: mango
     spec:
        containers:
        - name: con1
          image: nginx:latest
          ports: 
          - containerPort: 80
          volumeMounts:
          - name: myvol
            mountPath: /data
        - name: con2
          image: tomcat:latest
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: myvol
            mountPath: /new-data

        volumes:
        - name: myvol
          emptyDir: {}
        - name: myvol-2
          emptyDir: {}

 
---
apiVersion: v1
kind: Service
metadata:
  name: mydep-svc
spec:
  type: NodePort
  selector:
    app: mango
  ports:
  - port: 80
    #    nodePort: 30123


