apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp-http
  name: liv-htpp
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  - image: tomcat:latest
    name: con2
    ports:
    - containerPort: 8080
    

