apiVersion: v1
kind: Service
metadata:
  name: mypod-svc 
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30123
  selector:
    app: myapp
  type: NodePort
