apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mydb
  name: mysql
spec:
  containers:
  - image: mysql:5.7
    name: con2
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test123
    - name: MYSQL_DATABASE
      value: wordpress
    ports:
    - containerPort: 3306
    
---

apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
spec:
  ports:
  - name: port-1
    port: 3306
  selector:
    app: mydb
  type: ClusterIP
