apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
  - image: tomcat:latest
    name: con2
    ports:
    - containerPort: 8080
  nodeName: node21
    

      
