apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod-res
spec:
  containers:
  - image: nginx:latest
    name: con1
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - image: tomcat:latest
    name: con2
    ports:
    - containerPort: 8080
    

      
